### PR TITLE
Feat/user ministry

### PR DESCRIPTION
**Pull request by berryboylb**
i don't know why i'm having conflicts

### CODE REVIEW

**Comment by EphraimDev** [comment]
To solve it
1. Make a pull request and merge from hng develop branch to your forked repo. 
2. Then pull to your local and fix the merge issues 
3. Make a new commit

**Comment by berryboylb** [comment]
I don't understand I've tried pulling develope it says it's up to date

**Comment by EphraimDev** [comment]
Click the web editor and removd strange lines from the css file. Then make a commit

**Comment by berryboylb** [comment]
There are no lines here except from comment can you reach me on Whatsapp
+2349071077753 so I can send it in zipped format for you to see

**Comment by goodhands** [comment]
Lol, he won't reach you on WhatsApp @berryboylb. Your style.css has conflicts with the develop branch. 

Resolve your conflict by clicking the "Resolve Conflict" button and remove any weird code from your file:
berryBoyConflicts

**Pull request closed without merging**
